
# build the image on PRs

name: PR

on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - '.github/workflows/master.yml'
      - '.github/workflows/*release.yml'

jobs:
  pr-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: nelonoel/branch-name@v1.0.1

      - name: Create Short Commit Sha
        id: sha_short
        if: success()
        run: echo ::set-output name=SHA_SHORT::$(git rev-parse --short HEAD)

      - uses: earthly/actions/setup-earthly@v1
        with:
          version: v0.7.21

      - name: Build
        if: success()
        env:
          VERSION: ${{ steps.sha_short.outputs.SHA_SHORT }}
          EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
        run: earthly --org earthly-technologies --sat ido-sat --no-output --ci +all --VERSION=$VERSION

